### ISSUE TITLE
Error while training the model

### ISSUE THREAD

**Issue by FranciscoSola** [danielelic/deep-segmentation#3]
Hi Daniele,

I'm trying to train the model according to the "Run" section but when I run the command python train_unet3_conv.py I get this:

(...)
------------------------------
Fitting model (bit = 8) ...
------------------------------
**Train on 0 samples, validate on 0 samples**
Epoch 1/200
Traceback (most recent call last):
  File "train_unet3_conv.py", line 232, in <module>
    train_and_predict(8)
  File "train_unet3_conv.py", line 186, in train_and_predict
    callbacks=[csv_logger, model_checkpoint])
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 217, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

Apparently there's no samples to train or to validate, but the npy folder is (i guess) well created.

How can I solve this? is there something I'm missing?

Thanks a lot

**Comment by FranciscoSola** [comment]
I tried:

**Comment by FranciscoSola** [comment]
I tried:

import numpy as np
f = np.load(...\segmentation\npy\images_train.npy") 
f.size

and I get 0 as a result. As I understand, this means the images_train.npy array is empty

**Comment by danielelic** [comment]
Hi Francisco, 

did you download the dataset?

**Comment by FranciscoSola** [comment]
Yes, There was an issue with the paths. I could solve it. Thanks!
